package com.example.expenses.enums;

public enum Steps {
    START,
    HOME,
    LANGUAGE,
    REPORT,

    SUCCESS_REGISTRATION,
    SUCCESS_PROFILE_SAVE,

    PROFILE,
    PROFILE_EDIT,

    EDIT_FIRSTNAME,
    EDIT_LASTNAME,
    EDIT_PHONE_NUMBER,

    EXPENSE,
    ASK_EXPENSE_AMOUNT,
    ASK_EXPENSE_DESCRIPTION,
    ASK_CONFIRMATION_EXPENSE,

    INCOME,
    ASK_INCOME_AMOUNT,
    ASK_INCOME_DESCRIPTION,
    ASK_CONFIRMATION_INCOME,

    MONTHLY_REPORT,
    YEARLY_REPORT,
    MONTHLY_INCOME_REPORT,
    MONTHLY_EXPENSE_REPORT,
    YEARLY_INCOME_REPORT,
    YEARLY_EXPENSE_REPORT,
}
