package com.example.expenses.enums;

public enum Steps {
    START,
    HOME,
    LANGUAGE,
    REPORT,

    SUCCESS_REGISTRATION,
    SUCCESS_PROFILE_SAVE,

    PROFILE,
    PROFILE_EDIT,

    EDIT_FIRSTNAME,
    EDIT_LASTNAME,
    EDIT_PHONE_NUMBER,

    EXPENSE,
    ASK_EXPENSE_AMOUNT,
    ASK_EXPENSE_DESCRIPTION,
    ASK_CONFIRMATION_EXPENSE,

    INCOME,
    ASK_INCOME_AMOUNT,
    ASK_INCOME_DESCRIPTION,
    ASK_CONFIRMATION_INCOME,

    MONTHLY_REPORT,
    YEARLY_REPORT,
    MONTHLY_INCOME_REPORT,
    YEARLY_INCOME_REPORT,
    MONTHLY_INCOME_REPORT_FORMAT_SELECTION,
    YEARLY_INCOME_REPORT_FORMAT_SELECTION,
    MONTHLY_INCOME_REPORT_TEXT_FORMAT,
    MONTHLY_INCOME_REPORT_EXCEL_FORMAT,
    MONTHLY_OUTCOME_REPORT_TEXT_FORMAT,
    MONTHLY_OUTCOME_REPORT_EXCEL_FORMAT,
    YEARLY_INCOME_REPORT_TEXT_FORMAT,
    YEARLY_INCOME_REPORT_EXCEL_FORMAT,
    YEARLY_OUTCOME_REPORT_TEXT_FORMAT,
    YEARLY_OUTCOME_REPORT_EXCEL_FORMAT,

    SET_FIRSTNAME,
    SET_LASTNAME,
    SET_USERNAME,
    SET_PHONE_NUMBER,

    ASK_FIRST_NAME,
    ASK_LAST_NAME,
    ASK_CURRENT_INCOME,
    ASK_CURRENT_OUTCOME,
}
