spring:
  application:
    name: expenses-manager
  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5433/my_expense
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      keepalive-time: 300000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: never
  main:
    allow-bean-definition-overriding: true

server:
  port: 7777
telegram:
  bot:
    token: '7582548590:AAEANHiedDffD_3A_AGhULPzdS9GMNPQ5Mw'
    username: '@my_expenses_manager_bot'

    ### spring.main.allow-circular-references